// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0dKEAUQDi1XVrttjWvlijl7TPPMtcq_A',
    appId: '1:793868896092:web:49989006a1725d00e32399',
    messagingSenderId: '793868896092',
    projectId: 'fir-prac-e1ef7',
    authDomain: 'fir-prac-e1ef7.firebaseapp.com',
    storageBucket: 'fir-prac-e1ef7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLgfCJE1em-2yHOw7Bec-Fb7sv29qt0w',
    appId: '1:793868896092:android:c02747ddbd04d6e2e32399',
    messagingSenderId: '793868896092',
    projectId: 'fir-prac-e1ef7',
    storageBucket: 'fir-prac-e1ef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uvcS719zl62j0gHKjJB1XAUSrXmjkbw',
    appId: '1:793868896092:ios:1359c0614b24e3dee32399',
    messagingSenderId: '793868896092',
    projectId: 'fir-prac-e1ef7',
    storageBucket: 'fir-prac-e1ef7.appspot.com',
    iosClientId: '793868896092-jjrocf9gv1kg4o3jig81an4eqvpg8bcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasepractical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7uvcS719zl62j0gHKjJB1XAUSrXmjkbw',
    appId: '1:793868896092:ios:1359c0614b24e3dee32399',
    messagingSenderId: '793868896092',
    projectId: 'fir-prac-e1ef7',
    storageBucket: 'fir-prac-e1ef7.appspot.com',
    iosClientId: '793868896092-jjrocf9gv1kg4o3jig81an4eqvpg8bcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasepractical',
  );
}
